package com.example.demo.models;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.domain.Persistable;

import java.util.Date;

@Getter
@Setter
@MappedSuperclass
public class BaseModel implements Persistable<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Telling springboot that id is generated by Database
    private Long id;

    private Date createdAt;
    private Date lastUpdatedAt;
    private boolean isDeleted;

    @Override
    public Long getId() {
        return id;
    }

    // 🔥 THIS LINE SOLVES YOUR MAIN BUG
    @Override
    public boolean isNew() {
        return this.id == null;
    }

}
